name: Update Dependencies

on:
  push:
  schedule:
    - cron: '0 0 * * *' # daily

jobs:
  update:
    name: Update Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}

      - name: Install Nix shell
        uses: diamondburned/cache-install@main
        with:
          shell-file: shell.nix

      - name: Update Go Workspace
        run: |
          go work use $(find . -name go.mod -exec dirname {} \;)

      - name: Update dependencies
        run: |
          go get -u ./...
          go get go4.org/unsafe/assume-no-moving-gc@latest
          go mod tidy
          go work sync

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Update dependencies

  build:
    name: Build
    needs: update
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.ref_name }}

      - name: Install Nix shell
        uses: diamondburned/cache-install@main
        with:
          shell-file: shell.nix

      - name: Build
        run: go build ./...
